server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/wallet_db
    username: wallet_user
    password: wallet_pass
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    show-sql: true

  data:
    redis:
      host: localhost
      port: 6379

  cache:
    type: redis

jwt:
  secret: MyVerySecretKeyForJwtSigning
  expiration: 3600000

logging:
  level:
    root: INFO
    org.springframework: INFO
    com.example.wallet: DEBUG


springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    path: /swagger-ui.html